/* tslint:disable */
/* eslint-disable */
/**
 * API for MontyHall
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SimulateGamesRequest,
  SimulateGamesResponse,
} from '../models';
import {
    SimulateGamesRequestFromJSON,
    SimulateGamesRequestToJSON,
    SimulateGamesResponseFromJSON,
    SimulateGamesResponseToJSON,
} from '../models';

export interface ApiMontyhallSimulatePostRequest {
    simulateGamesRequest: SimulateGamesRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async apiMontyhallSimulatePostRaw(requestParameters: ApiMontyhallSimulatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimulateGamesResponse>> {
        if (requestParameters.simulateGamesRequest === null || requestParameters.simulateGamesRequest === undefined) {
            throw new runtime.RequiredError('simulateGamesRequest','Required parameter requestParameters.simulateGamesRequest was null or undefined when calling apiMontyhallSimulatePost.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/montyhall/simulate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SimulateGamesRequestToJSON(requestParameters.simulateGamesRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimulateGamesResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiMontyhallSimulatePost(requestParameters: ApiMontyhallSimulatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimulateGamesResponse> {
        const response = await this.apiMontyhallSimulatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
