/* tslint:disable */
/* eslint-disable */
/**
 * API for MontyHall
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * stats for the simulated games
 * @export
 * @interface OutputData
 */
export interface OutputData {
    /**
     * percent of games won
     * @type {number}
     * @memberof OutputData
     */
    percentWon: number;
    /**
     * percent of games lost
     * @type {number}
     * @memberof OutputData
     */
    percentLost: number;
}

/**
 * Check if a given object implements the OutputData interface.
 */
export function instanceOfOutputData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "percentWon" in value;
    isInstance = isInstance && "percentLost" in value;

    return isInstance;
}

export function OutputDataFromJSON(json: any): OutputData {
    return OutputDataFromJSONTyped(json, false);
}

export function OutputDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): OutputData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'percentWon': json['percentWon'],
        'percentLost': json['percentLost'],
    };
}

export function OutputDataToJSON(value?: OutputData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'percentWon': value.percentWon,
        'percentLost': value.percentLost,
    };
}

