/* tslint:disable */
/* eslint-disable */
/**
 * API for MontyHall
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OutputData } from './OutputData';
import {
    OutputDataFromJSON,
    OutputDataFromJSONTyped,
    OutputDataToJSON,
} from './OutputData';

/**
 * holds the values returned to frontend
 * @export
 * @interface SimulateGamesResponse
 */
export interface SimulateGamesResponse {
    /**
     * 
     * @type {OutputData}
     * @memberof SimulateGamesResponse
     */
    outputData: OutputData;
}

/**
 * Check if a given object implements the SimulateGamesResponse interface.
 */
export function instanceOfSimulateGamesResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "outputData" in value;

    return isInstance;
}

export function SimulateGamesResponseFromJSON(json: any): SimulateGamesResponse {
    return SimulateGamesResponseFromJSONTyped(json, false);
}

export function SimulateGamesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimulateGamesResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'outputData': OutputDataFromJSON(json['outputData']),
    };
}

export function SimulateGamesResponseToJSON(value?: SimulateGamesResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'outputData': OutputDataToJSON(value.outputData),
    };
}

