/* tslint:disable */
/* eslint-disable */
/**
 * API for MonthlyHall
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * stats for the simulated games
 * @export
 * @interface Stats
 */
export interface Stats {
    /**
     * percent of games won
     * @type {number}
     * @memberof Stats
     */
    percentWon: number;
    /**
     * percent of games lost
     * @type {number}
     * @memberof Stats
     */
    percentLost: number;
}

/**
 * Check if a given object implements the Stats interface.
 */
export function instanceOfStats(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "percentWon" in value;
    isInstance = isInstance && "percentLost" in value;

    return isInstance;
}

export function StatsFromJSON(json: any): Stats {
    return StatsFromJSONTyped(json, false);
}

export function StatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'percentWon': json['percentWon'],
        'percentLost': json['percentLost'],
    };
}

export function StatsToJSON(value?: Stats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'percentWon': value.percentWon,
        'percentLost': value.percentLost,
    };
}

